name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  typescript:
    name: TypeScript & JavaScript
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: TypeScript check
        run: npx tsc --noEmit

      - name: Build module
        run: npm run build

      - name: Install example dependencies
        working-directory: ./example
        run: npm ci

      - name: TypeScript check (example)
        working-directory: ./example
        run: npx tsc --noEmit

  android:
    name: Android & Kotlin
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Node.js (for expo-module-scripts)
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci

      - name: Install example dependencies
        working-directory: ./example
        run: npm ci

      - name: Build Android module
        working-directory: ./example/android
        run: ./gradlew :expo-accessibility-service:build

      - name: Run Kotlin lint (detekt)
        working-directory: ./example/android
        run: ./gradlew :expo-accessibility-service:detekt || echo "Detekt not configured, skipping"

      - name: Compile Kotlin sources
        working-directory: ./example/android
        run: ./gradlew :expo-accessibility-service:compileDebugKotlin

      - name: Build example Android app (APK)
        working-directory: ./example/android
        run: ./gradlew assembleDebug